DROP TABLE IF EXISTS mm_measurements CASCADE;
DROP TABLE IF EXISTS mm_vendors CASCADE;
DROP TABLE IF EXISTS mm_warehouse CASCADE;
DROP TABLE IF EXISTS mm_manufacturing CASCADE;
DROP TABLE IF EXISTS mm_purchasing CASCADE;
DROP TABLE IF EXISTS mm_materials CASCADE;
DROP TABLE IF EXISTS mm_categories CASCADE;
